name: "Workflow Timer"
description: "Measures the duration of the workflow and reports to dashboard"
inputs:
  name:
    description: "Name of the workflow"
    required: true
  metrics-provider:
    description: "The metrics provider to be used"
  DATADOG_API_KEY:
    description: "Datadog api key to report metrics"
  DATADOG_HOST:
    description: "Datadog host to report metrics"
  gh_token:
    description: "github token to use for commiting to repo"
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: duration
      with:
        script: |
          const currentTime = new Date().getTime();
          const currentRun = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const startedAt = currentRun.data.run_started_at
          const currentRunDurationInMillis = currentTime - new Date(startedAt).getTime();
          core.setOutput('DURATION', currentRunDurationInMillis)

    - run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        export GH_TOKEN=${{inputs.gh_token}}
        echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
      shell: bash

    - run: |
         if [ '${{ inputs.metrics-provider }}' = 'datadog' ]; then
           export "SFPOWERSCRIPTS_DATADOG=true" 
           export "SFPOWERSCRIPTS_DATADOG_HOST=${{ inputs.DATADOG_HOST }}"
           export "SFPOWERSCRIPTS_DATADOG_API_KEY=${{ inputs.DATADOG_API_KEY }}"
          fi
          sfp metrics:report -m 'workflow.duration' -v ${{ steps.duration.outputs.DURATION }} -t timer -g {\"workflow\":\"${{inputs.name}}\"}
      shell: bash

         