name: "Create Repository Environments"
description: "Create deployment environments for repositories"
author: "Flxbl.io"
inputs:
  repo:
    description: "Repository name incl owner/org"
    required: true
  token:
    description: "Github token with the scope 'repo'"
    required: true
  environments:
    description: "Environments e.g. 'test,prod'"
    required: true
  required_reviewers:
    description: "Required reviewers e.g. 'org/team,user' max 6"
  wait_time:
    description: "Wait time in minutes"
    default: 0
  protected_branches_only:
    description: "Only protected branches can be deployed"
    default: false

runs:
  using: "node20"
  main: "dist/index.js"
