name: 'IssueOps - Close an issue'

on:
  workflow_call:
     inputs:
        issue-title: 
          description: "The title of the issue"
          type: "string"
        issue-body: 
          description: "The body of the issue"
          type: "string"
        issue-number:
          description: "The number of the issue"
          type: "string"
        metrics-provider:
          description: "The metrics provider to be used"
          type: "string"
        sfopsbot-app-id: 
          description: The App id of the bot used for this workflow_call
          type: "string"
        dashboard-repo: 
          description: Dashboard repo where any reports need to be push
          type: "string"          
     secrets:
      NPM_TOKEN:
        description: "GH TOKEN to publish to NPM"
      DEVHUB_SFDX_AUTH_URL:
        description: "Devhub Auth URL"
      SB_SFDX_AUTH_URL:
        description: "Sandbox Auth URL"
      DATADOG_API_KEY:
        description: "Datadog api key to report metrics"
      DATADOG_HOST:
        description: "Datadog host to report metrics"
      SFOPSBOT_APP_PRIVATE_KEY:
        description: "Private key of the bot app used"


jobs:

  analyze_issue:
      runs-on: ubuntu-latest
      outputs:
        sfops_issue: ${{ steps.sfops_issue_analyzer.outputs.sfops_issue }}
        sfops_issue_envs: ${{ steps.sfops_issue_analyzer.outputs.sfops_issue_envs }}
      steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.sfopsbot-app-id }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
  
      - name: Analyze Issue
        uses: flxbl-azlam/sfops-gh-actions/issueAnalyzer@main
        id: sfops_issue_analyzer
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          issue: ${{ github.event.issue.number }}
          token: ${{ steps.app-token.outputs.token }}

       # gh needs checking out
      - name: Checkout Repository
        if: ${{ steps.sfops_issue_analyzer.outputs.sfops_issue == 'false'}}
        uses: actions/checkout@v4


      - name: Cancel deployment if no changes
        id: cancel-if-necessary
        if: ${{ steps.sfops_issue_analyzer.outputs.sfops_issue == 'false'}}
        run: |
            echo "Not an sfops issue or its excluded,  Cancelling workflow run."
            gh run cancel ${{ github.run_id }}
        env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}

  close_issue:
      runs-on: ubuntu-latest
      container: ghcr.io/flxbl-azlam/sfops-gh-actions-lite:latest
      needs:
        - analyze_issue
      if: needs.analyze_issue.outputs.sfops_issue == 'true'
      strategy:
        fail-fast: false
        matrix:
          environment: ${{ fromJSON(needs.analyze_issue.outputs.sfops_issue_envs) }}
      environment:
          name: ${{ matrix.environment }}
      outputs:
        created_envs: ${{ steps.track-envs.outputs.created_envs }}
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.sfopsbot-app-id }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: 'Authenticate DevHub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfp org login -f authfile -a devhub
  
      - name: Authenticate to environment - ${{ matrix.environment }}
        id: handle-auth
        if: ${{ matrix.environment != 'devhub' }}
        uses: flxbl-azlam/sfops-gh-actions/authToEnvironment@main
        with:
          DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
          SB_SFDX_AUTH_URL: ${{ secrets.SB_SFDX_AUTH_URL }}
          environment: ${{ matrix.environment }}
          org-name: ${{ vars.SBXNAME  || vars.SBX_NAME }}
          environment-profile: ${{ matrix.environment }}

           
      - name: 'Close Issue'
        id: execute_issue
        if: steps.handle-auth.conclusion == 'success' || matrix.environment == 'devhub'
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY}}
          SFOPSBOT_APP_ID: ${{ inputs.sfopsbot-app-id }}
        run: |
            sfp gh issue run -i ${{ github.event.issue.number }} -p env=${{ matrix.environment }}  -r ${{ github.repository }} -a close || true 
          

      - uses: actions/create-github-app-token@v1
        name: Get a refreshed app token
        if: always()
        id: app-token-refreshed
        with:
          app-id: ${{ inputs.sfopsbot-app-id }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: "Push changes to dev central"
        id: updateGitRepo
        uses: flxbl-azlam/sfops-gh-actions/updateGitRepo@main
        if: ${{ steps.execute_issue.outcome == 'success' && steps.execute_issue.outputs.sfops_devcentral_update_required == 'true'}}
        with:
         target-repo: ${{ inputs.dashboard-repo }}
         source-dir: _data
         target-dir: _data
         commit-message: ${{ steps.execute_issue.outputs.sfops_devcentral_commit_message || 'Update devcentral' }}
         update-release-names: false
         gh_token: ${{ steps.app-token-refreshed.outputs.token }}

  cleanup_environments:
    needs: analyze_issue
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.sfopsbot-app-id }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: 'Fetch All Envs'
        id: fetch-all-envs
        uses: flxbl-azlam/sfops-gh-actions/fetchAllEnvs@main
        with:
          gh_token: ${{ steps.app-token.outputs.token }}

      - name: 'Delete non sfops environments'
        id: delete-non-sfops-envs
        uses: flxbl-azlam/sfops-gh-actions/deleteEnvironments@main
        continue-on-error: true
        with:
          token: ${{ steps.app-token.outputs.token }}
          exclude_environments: ${{ steps.fetch-all-envs.outputs.allEnvs }}